class HokomakuInfo {
	/**
	 * 
	 * @param {string} routeNumber 系統番号
	 * @param {string} subRouteNumber 補助系統番号
	 * @param {string} routeColor 系統色
	 * @param {string} street 通り名
	 * @param {string} subDest 経由地
	 * @param {string} mainDest 行き先
	 * @param {string} englishDest 行き先(英語)
	 * @param {bool} isDoubleLine 二重線にするか
	 */
	constructor(routeObj, street, subDest, mainDest, englishDest, isDoubleLine) {
		this.routeNumber = routeObj.number;
		this.subRouteNumber = routeObj.sub;
		this.routeColor = routeObj.color;
		this.isReverse = routeObj.isReverse;
		this.street = street;
		this.subDest = subDest;
		this.mainDest = mainDest;
		this.englishDest = englishDest;
		this.isDoubleLine = isDoubleLine || false;
	}
}

function scaleXL(str, scale) { return `<span style="display: inline-block; transform: scaleX(${scale}); transform-origin: left;">${str}</span>`; }
function scaleXC(str, scale) { return `<span style="display: inline-block; transform: scaleX(${scale}); transform-origin: center;">${str}</span>`; }
function size(str, size) { return `<span style="display: inline-block; font-size: ${size}; line-height: 1;">${str}</span>`; }
function sizeTop(str, size) { return `<span style="display: inline-block; font-size: ${size}; line-height: 1; vertical-align: top;">${str}</span>`; }
function sizeBottom(str, size) { return `<span style="display: inline-block; font-size: ${size}; line-height: 1; vertical-align: bottom;">${str}</span>`; }
function sizeMax(str, size, max) { return `<span style="display: inline-block; font-size: ${size}; line-height: 1; max-width: ${max}">${str}</span>`; }
function sizeWidth(str, size, width) { return `<span style="display: inline-block; font-size: ${size}; line-height: 1; width: ${width}">${str}</span>`; }
function letterSpacing(str, letterSpacing) { return `<span style="display: inline-block; letter-spacing: ${letterSpacing}">${str}</span>`; }
function kitaojiBT(widthEm, fontSize, height) { return `<span style="font-size: ${fontSize}rem; display: flex; flex-direction: column; line-height: 1; width: ${widthEm}em; transform-origin: bottom center;">
		${Center.getCenter("北大路バスターミナル", widthEm, height || 1.4, `${fontSize}rem`)}
		${Center.getCenter("(地下鉄北大路駅)", widthEm / 0.4, 1, `${fontSize * 0.4}rem`)}
		<span></span>
	</span>` }
function made() { return `<span style="font-size: 60%; line-height: 1; background-color: white; color: black; margin-left: 5px;">まで</span>` }
function north(number) { return `<span style="display: inline-block; font-size: 80%; transform: translateY(-0.07em);">北</span>${number}` }
function tlX(str, number) { return `<span style="display: inline-block; transform: translateX(${number});">${str}</span>` }
function route(before, str, after) { return `<span style="display: inline-block; font-size: 80%; transform: translateY(-0.07em); font-weight: 600;">${before}</span>${str}<span style="display: inline-block; font-size: 80%; transform: translateY(-0.07em); font-weight: 600;">${after}</span>` }

const KYOTO_CITY_BUS_ROUTE = {
	/* 0番台 */
	"1": {number: scaleXC("1", 1.5), sub: "", color: "normal"},
	"1甲": {number: `${route("", "1", "甲")}`, sub: "", color: "normal"},
	"1乙": {number: `${route("", "1", "乙")}`, sub: "", color: "normal"},
	"特1": {number: `${route("特", "1", "")}`, sub: "", color: "normal"},
	"快速1": {number: `${route("", sizeTop(scaleXC("1", 1.75), "65%"), "")}`, sub: Center.getCenter("<span style=\"color: var(--route-normal-color); display: inline-block; transform: translateY(2.5px)\">"+"快速 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Rapid</span>"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"2": {number: scaleXC("2", 1.5), sub: "", color: "normal"},
	"2甲": {number: `${route("", "2", "甲")}`, sub: "", color: "normal"},
	"特2": {number: `${route("特", "2", "")}`, sub: "", color: "normal"},
	"3": {number: scaleXC("3", 1.5), sub: "", color: "normal"},
	"3甲": {number: `${route("", "3", "甲")}`, sub: "", color: "normal"},
	"三条京阪3": {number: `${route("", sizeTop(scaleXC("3", 1.75), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"三条京阪"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"上終町3": {number: `${route("", sizeTop(scaleXC("3", 1.75), "65%"), "")}`, sub: "<span style=\"display: inline-block; transform: translateY(-1px);\">"+"上終町"+"</span>", color: "normal"},
	"4": {number: scaleXC("4", 1.5), sub: "", color: "normal"},
	"4甲": {number: `${route("", "4", "甲")}`, sub: "", color: "normal"},
	"4乙": {number: `${route("", "4", "乙")}`, sub: "", color: "normal"},
	"4丙": {number: `${route("", "4", "丙")}`, sub: "", color: "normal"},
	"N4": {number: `${route("", "N4", "")}`, sub: "", color: "normal"},
	"松ヶ崎4": {number: `${route("", sizeTop(scaleXC("4", 1.75), "65%"), "")}`, sub: "<span style=\"display: inline-block; transform: translateY(-1px);\">"+"松ヶ崎"+"</span>", color: "normal"},
	"上賀茂小4": {number: `${route("", sizeTop(scaleXC("4", 1.75), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"上賀茂小"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"5": {number: scaleXC("5", 1.5), sub: "", color: "normal"},
	"5甲": {number: `${route("", "5", "甲")}`, sub: "", color: "normal"},
	"N5": {number: `${route("", "N5", "")}`, sub: "", color: "normal"},
	"特5": {number: `${route("特", "5", "")}`, sub: "", color: "seiriken"},
	"臨5": {number: `${route("臨", "5", "")}`, sub: "", color: "seiriken"},
	"6": {number: scaleXC("6", 1.5), sub: "", color: "normal"},
	"6甲": {number: `${route("", "6", "甲")}`, sub: "", color: "normal"},
	"快速6": {number: `${route("", sizeTop(scaleXC("6", 1.75), "65%"), "")}`, sub: Center.getCenter("<span style=\"color: var(--route-normal-color); display: inline-block; transform: translateY(2.5px)\">"+"快速 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Rapid</span>"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"四条大宮6": {number: `${route("", sizeTop(scaleXC("6", 1.75), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"四条大宮"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"7": {number: scaleXC("7", 1.5), sub: "", color: "normal"},
	"7甲": {number: `${route("", "7", "甲")}`, sub: "", color: "normal"},
	"7乙": {number: `${route("", "7", "乙")}`, sub: "", color: "normal"},
	"8": {number: scaleXC("8", 1.5), sub: "", color: "normal"},
	"特8": {number: `${route("特", "8", "")}`, sub: "", color: "seiriken"},
	"9": {number: scaleXC("9", 1.5), sub: "", color: "normal"},
	"N9": {number: `${route("", "N9", "")}`, sub: "", color: "normal"},
	"快9": {number: `${route("快", "9", "")}`, sub: "", color: "normal"},
	/* 10番台 */
	"10": {number: "10", sub: "", color: "normal"},
	"10甲": {number: `${Center.getCenter(route("", "10", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"11": {number: "11", sub: "", color: "normal"},
	"11甲": {number: `${Center.getCenter(route("", "11", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"三条京阪11": {number: `${route("", sizeTop(scaleXC("11", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"三条京阪"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"12": {number: "12", sub: "", color: "normal"},
	"12甲": {number: `${Center.getCenter(route("", "12", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"13": {number: "13", sub: "", color: "normal"},
	"13甲": {number: `${Center.getCenter(route("", "13", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"N13": {number: `${Center.getCenter(route("", "N13", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"特13": {number: `${Center.getCenter(route("特", "13", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"臨13": {number: `${Center.getCenter(route("臨", "13", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"14": {number: "14", sub: "", color: "normal"},
	"15": {number: "15", sub: "", color: "normal"},
	"15甲": {number: `${Center.getCenter(route("", "15", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"快速15": {number: `${route("", sizeTop(scaleXC("15", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"color: var(--route-normal-color); display: inline-block; transform: translateY(2.5px)\">"+"快速 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Rapid</span>"+"</span>", 3.5, 1, "", 4), color: "normal"},
	"16": {number: "16", sub: "", color: "normal"},
	"16甲": {number: `${Center.getCenter(route("", "16", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"16乙": {number: `${Center.getCenter(route("", "16", "乙"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"17": {number: "17", sub: "", color: "normal"},
	"17甲": {number: `${Center.getCenter(route("", "17", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"特17": {number: `${Center.getCenter(route("特", "17", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"MN17": {number: `${route("", sizeTop(scaleXC("17", 1.5), "65%"), "")}`, sub: scaleXC("<span style=\"display: inline-block;\">"+"ＭＮ"+"</span>", 1.5), color: "normal"},
	"18": {number: "18", sub: "", color: "normal"},
	"18甲": {number: `${Center.getCenter(route("", "18", "甲"), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"特18": {number: `${Center.getCenter(route("特", "18", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"臨18": {number: `${Center.getCenter(route("臨", "18", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"竹田駅18": {number: `${route("", sizeTop(scaleXC("18", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"竹田駅"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"二条駅18": {number: `${route("", sizeTop(scaleXC("18", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"二条駅"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"二条駅特18": {number: `${route("", sizeTop(scaleXC(route("特", "18", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"二条駅"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"二条駅臨18": {number: `${route("", sizeTop(scaleXC(route("臨", "18", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"二条駅"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"19": {number: "19", sub: "", color: "normal"},
	"特19": {number: `${Center.getCenter(route("特", "19", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	/* 20番台 */
	"20": {number: "20", sub: "", color: "normal"},
	"特20": {number: `${Center.getCenter(route("特", "20", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"伏見港20": {number: `${route("", sizeTop(scaleXC("20", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"伏見港"+"</span>", 3.5, 1, "", 3), color: "seiriken"},
	"21": {number: "21", sub: "", color: "normal"},
	"21甲": {number: `${Center.getCenter(route("", "21", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"21乙": {number: `${Center.getCenter(route("", "21", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"21丙": {number: `${Center.getCenter(route("", "21", "丙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"22": {number: "22", sub: "", color: "normal"},
	"22甲": {number: `${Center.getCenter(route("", "22", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"22乙": {number: `${Center.getCenter(route("", "22", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特22": {number: `${Center.getCenter(route("特", "22", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"伏見港22": {number: `${route("", sizeTop(scaleXC("22", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"伏見港"+"</span>", 3.5, 1, "", 3), color: "seiriken"},
	"23": {number: "23", sub: "", color: "normal"},
	"23甲": {number: `${Center.getCenter(route("", "23", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"23乙": {number: `${Center.getCenter(route("", "23", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"24": {number: "24", sub: "", color: "normal"},
	"25": {number: "25", sub: "", color: "normal"},
	"25甲": {number: `${Center.getCenter(route("", "25", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"26": {number: "26", sub: "", color: "normal"},
	"26甲": {number: `${Center.getCenter(route("", "26", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"N26": {number: `${Center.getCenter(route("", "N26", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"27": {number: "27", sub: "", color: "normal"},
	"27甲": {number: `${Center.getCenter(route("", "27", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特27": {number: `${Center.getCenter(route("特", "27", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"28": {number: "28", sub: "", color: "normal"},
	"28甲": {number: `${Center.getCenter(route("", "28", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"29": {number: "29", sub: "", color: "normal"},
	"29甲": {number: `${Center.getCenter(route("", "29", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	/* 30番台 */
	"30": {number: "30", sub: "", color: "normal"},
	"30甲": {number: `${Center.getCenter(route("", "30", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"31": {number: "31", sub: "", color: "normal"},
	"32": {number: "32", sub: "", color: "normal"},
	"33": {number: "33", sub: "", color: "normal"},
	"33甲": {number: `${Center.getCenter(route("", "33", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特33": {number: `${Center.getCenter(route("特", "33", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"34": {number: "34", sub: "", color: "normal"},
	"35": {number: "35", sub: "", color: "normal"},
	"36": {number: "36", sub: "", color: "normal"},
	"37": {number: "37", sub: "", color: "normal"},
	"37甲": {number: `${Center.getCenter(route("", "37", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特37": {number: `${Center.getCenter(route("特", "37", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"38": {number: "38", sub: "", color: "normal"},
	"38甲": {number: `${Center.getCenter(route("", "38", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"39": {number: "39", sub: "", color: "normal"},
	"39甲": {number: `${Center.getCenter(route("", "39", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"39乙": {number: `${Center.getCenter(route("", "39", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特39": {number: `${Center.getCenter(route("特", "39", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	/* 40番台 */
	"40": {number: "40", sub: "", color: "normal"},
	"40甲": {number: `${Center.getCenter(route("", "40", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"40乙": {number: `${Center.getCenter(route("", "40", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特40": {number: `${Center.getCenter(route("特", "40", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"N40": {number: `${Center.getCenter(route("", "N40", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"41": {number: "41", sub: "", color: "normal"},
	"41甲": {number: `${Center.getCenter(route("", "41", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"41乙": {number: `${Center.getCenter(route("", "41", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特41甲": {number: `${Center.getCenter(route("特", "41", "甲"), 1.4, 1, "", 2.9)}`, sub: "", color: "normal"},
	"特41乙": {number: `${Center.getCenter(route("特", "41", "乙"), 1.4, 1, "", 2.9)}`, sub: "", color: "normal"},
	"42": {number: "42", sub: "", color: "normal"},
	"42甲": {number: `${Center.getCenter(route("", "42", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特42": {number: `${Center.getCenter(route("特", "42", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"43": {number: "42", sub: "", color: "normal"},
	"43甲": {number: `${Center.getCenter(route("", "43", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"44": {number: "44", sub: "", color: "normal"},
	"44甲": {number: `${Center.getCenter(route("", "44", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"45": {number: "45", sub: "", color: "normal"},
	"46": {number: "46", sub: "", color: "normal"},
	"47": {number: "47", sub: "", color: "normal"},
	"47甲": {number: `${Center.getCenter(route("", "47", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"48": {number: "48", sub: "", color: "normal"},
	"49": {number: "49", sub: "", color: "normal"},
	"49甲": {number: `${Center.getCenter(route("", "49", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"49A": {number: `${Center.getCenter(route("", "49A", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"49C": {number: `${Center.getCenter(route("", "49C", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"特49": {number: `${Center.getCenter(route("特", "49", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	/* 50番台 */
	"50": {number: "50", sub: "", color: "normal"},
	"51": {number: "51", sub: "", color: "normal"},
	"特51": {number: `${Center.getCenter(route("特", "51", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"52": {number: "52", sub: "", color: "normal"},
	"53": {number: "53", sub: "", color: "normal"},
	"54": {number: "54", sub: "", color: "normal"},
	"54甲": {number: `${Center.getCenter(route("", "54", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"54乙": {number: `${Center.getCenter(route("", "54", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"55": {number: "55", sub: "", color: "normal"},
	"56": {number: "56", sub: "", color: "normal"},
	"56甲": {number: `${Center.getCenter(route("", "56", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"57": {number: "57", sub: "", color: "normal"},
	"57C": {number: `${Center.getCenter(route("", "57C", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"58": {number: "58", sub: "", color: "normal"},
	"58甲": {number: `${Center.getCenter(route("", "58", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"59": {number: "59", sub: "", color: "normal"},
	"59甲": {number: `${Center.getCenter(route("", "59", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特59": {number: `${Center.getCenter(route("特", "59", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"臨59": {number: `${Center.getCenter(route("臨", "59", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"広沢池59": {number: `${route("", sizeTop(scaleXC("59", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"広沢池"+"</span>", 3.5, 1, "", 3), color: "seiriken"},
	/* 60番台 */
	"60": {number: "60", sub: "", color: "normal"},
	"60甲": {number: `${Center.getCenter(route("", "60", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"61": {number: "61", sub: "", color: "normal"},
	"62": {number: "62", sub: "", color: "normal"},
	"62甲": {number: `${Center.getCenter(route("", "62", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"63": {number: "63", sub: "", color: "normal"},
	"64": {number: "64", sub: "", color: "normal"},
	"64甲": {number: `${Center.getCenter(route("", "64", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"64乙": {number: `${Center.getCenter(route("", "64", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"64丙": {number: `${Center.getCenter(route("", "64", "丙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"64B": {number: `${Center.getCenter(route("", "64B", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"64甲B": {number: `${Center.getCenter(route("", "64", "甲")+`B`, 1.5, 1, "", 2.7)}`, sub: "", color: "normal"},
	"65": {number: "65", sub: "", color: "normal"},
	"66": {number: "66", sub: "", color: "normal"},
	"66甲": {number: `${Center.getCenter(route("", "66", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"67": {number: "67", sub: "", color: "normal"},
	"67甲": {number: `${Center.getCenter(route("", "67", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"68": {number: "68", sub: "", color: "normal"},
	"69": {number: "69", sub: "", color: "normal"},
	"69甲": {number: `${Center.getCenter(route("", "69", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特69": {number: `${Center.getCenter(route("特", "69", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	/* 70番台 */
	"70": {number: "70", sub: "", color: "normal"},
	"71": {number: "71", sub: "", color: "normal"},
	"太秦天神川71": {number: `${route("", sizeTop(scaleXC("71", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"太秦天神川"+"</span>", 3.5, 1, "", 5), color: "normal"},
	"特71": {number: `${Center.getCenter(route("特", "71", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"72": {number: "72", sub: "", color: "normal"},
	"72甲": {number: `${Center.getCenter(route("", "72", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"72乙": {number: `${Center.getCenter(route("", "72", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"73": {number: "73", sub: "", color: "normal"},
	"73甲": {number: `${Center.getCenter(route("", "73", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"74": {number: "74", sub: "", color: "normal"},
	"75": {number: "75", sub: "", color: "normal"},
	"75甲": {number: `${Center.getCenter(route("", "75", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"75乙": {number: `${Center.getCenter(route("", "75", "乙"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"76": {number: "76", sub: "", color: "normal"},
	"76甲": {number: `${Center.getCenter(route("", "76", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"77": {number: "77", sub: "", color: "normal"},
	"78": {number: "78", sub: "", color: "normal"},
	"特78": {number: `${Center.getCenter(route("特", "78", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	/* 80番台 */
	"80": {number: "80", sub: "", color: "normal"},
	"80甲": {number: `${Center.getCenter(route("", "80", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"80C": {number: `${Center.getCenter(route("", "80C", ""), 1.5, 1, "", 2)}`, sub: "", color: "normal"},
	"特80": {number: `${Center.getCenter(route("特", "80", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"81": {number: "81", sub: "", color: "normal"},
	"81甲": {number: `${Center.getCenter(route("", "81", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"特81": {number: `${Center.getCenter(route("特", "81", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	"特81A": {number: `${Center.getCenter(route("特", "81A", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "seiriken"},
	"特81B": {number: `${Center.getCenter(route("特", "81B", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "seiriken"},
	"伏見港81": {number: `${route("", sizeTop(scaleXC("81", 1.5), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"伏見港"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"竹田駅特81": {number: `${route("", sizeTop(scaleXC(route("特", "81", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"竹田駅"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"伏見港特81": {number: `${route("", sizeTop(scaleXC(route("特", "81", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"伏見港"+"</span>", 3.5, 1, "", 3), color: "normal"},
	"82": {number: "81", sub: "", color: "normal"},
	"82甲": {number: `${Center.getCenter(route("", "81", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"83": {number: "83", sub: "", color: "normal"},
	"84": {number: "84", sub: "", color: "normal"},
	"86": {number: "86", sub: "", color: "normal"},
	"88": {number: "88", sub: "", color: "normal"},
	/* 90番台 */
	"91": {number: "91", sub: "", color: "normal"},
	"91甲": {number: `${Center.getCenter(route("", "91", "甲"), 1.4, 1, "", 2)}`, sub: "", color: "normal"},
	"92": {number: "92", sub: "", color: "normal"},
	"93": {number: "93", sub: "", color: "normal"},
	"特93": {number: `${Center.getCenter(route("特", "93", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	/* 100番台 */
	"100": {number: Center.getCenter(100, 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行100": {number: sizeTop(scaleXC("100", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"101": {number: Center.getCenter(101, 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行101": {number: sizeTop(scaleXC("101", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"102": {number: Center.getCenter(102, 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行102": {number: sizeTop(scaleXC("102", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"103": {number: Center.getCenter(103, 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行103": {number: sizeTop(scaleXC("103", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"104": {number: Center.getCenter(104, 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行104": {number: sizeTop(scaleXC("104", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"急行105": {number: sizeTop(scaleXC("105", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"急行特105": {number: `<span style="display: inline-block; transform: translateX(-5px);">${sizeTop(scaleXC(route("特", "105", ""), 0.8), "65%")}</span>`, sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"急行106": {number: sizeTop(scaleXC("106", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"108": {number: Center.getCenter("108", 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"急行110": {number: sizeTop(scaleXC("110", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"急行111": {number: sizeTop(scaleXC("111", 1.3), "65%"), sub: Center.getCenter("<span style=\"color: var(--route-express-color);display: inline-block; transform: translateY(2.5px)\">"+"急行 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Exp.</span>"+"</span>", 3.5, 1, "", 3), color: "normal" },
	"112": {number: Center.getCenter("112", 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"113": {number: Center.getCenter("113", 1.5, 1, "100%", 2), sub: "", color: "normal"},
	/* 200番台 */
	"200": {number: Center.getCenter("200", 1.5, 1, "100%", 2), sub: "", color: "normal"},
	"200甲": {number: `${Center.getCenter(route("", "200", "甲"), 1.4, 1, "", 2.5)}`, sub: "", color: "normal"},
	"200乙": {number: `${Center.getCenter(route("", "200", "乙"), 1.4, 1, "", 2.5)}`, sub: "", color: "normal"},
	"201": {number: Center.getCenter("201", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"みぶ201": {number: `${route("", sizeTop(scaleXC("201", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"みぶ"+"</span>", 3.5, 1, "", 2), color: "loop"},
	"四条大宮201": {number: `${route("", sizeTop(scaleXC("201", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"四条大宮"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"二条駅201": {number: `${route("", sizeTop(scaleXC("201", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"二条駅"+"</span>", 3.5, 1, "", 3), color: "loop"},
	"202": {number: Center.getCenter("202", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"特202": {number: `${Center.getCenter(route("特", "202", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "loop"},
	"臨202": {number: `${Center.getCenter(route("臨", "202", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "loop"},
	"九条車庫202": {number: `${route("", sizeTop(scaleXC("202", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"九条車庫"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"八条口202": {number: `${route("", sizeTop(scaleXC("201", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"八条口"+"</span>", 3.5, 1, "", 3), color: "loop"},
	"快速202": {number: `${route("", sizeTop(scaleXC("202", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"color: var(--route-loop-color); display: inline-block; transform: translateY(2.5px)\">"+"快速 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Rapid</span>"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"203": {number: Center.getCenter("203", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"錦林車庫203": {number: `${route("", sizeTop(scaleXC("203", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"錦林車庫"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"204": {number: Center.getCenter("204", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"北大路BT204": {number: `${route("", sizeTop(scaleXC("204", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"北大路BT"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"MN204": {number: `${route("", sizeTop(scaleXC("204", 1.3), "65%"), "")}`, sub: scaleXC("<span style=\"display: inline-block;\">"+"ＭＮ"+"</span>", 1.5), color: "loop"},
	"205": {number: Center.getCenter("205", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"特205": {number: `${Center.getCenter(route("特", "205", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "loop"},
	"九条車庫205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"九条車庫"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"京都駅205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"京都駅"+"</span>", 3.5, 1, "", 3), color: "loop"},
	"北大路BT205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"北大路BT"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"烏丸北大路205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"烏丸北大路"+"</span>", 3.5, 1, "", 5), color: "loop"},
	"西大路四条205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"西大路四条"+"</span>", 3.5, 1, "", 5), color: "loop"},
	"四条河原町205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"四条河原町"+"</span>", 3.5, 1, "", 5), color: "loop"},
	"快速205": {number: `${route("", sizeTop(scaleXC("205", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"color: var(--route-loop-color); display: inline-block; transform: translateY(2.5px)\">"+"快速 <span style=\"font-size: 70%; display: inline-block; transform: translateY(-.2em)\">Rapid</span>"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"206": {number: Center.getCenter("206", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"京都駅206": {number: `${route("", sizeTop(scaleXC("206", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"京都駅"+"</span>", 3.5, 1, "", 3), color: "loop"},
	"北大路BT206": {number: `${route("", sizeTop(scaleXC("206", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"北大路BT"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"臨205": {number: `${Center.getCenter(route("臨", "205", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "loop"},
	"207": {number: Center.getCenter("207", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"九条車庫207": {number: `${route("", sizeTop(scaleXC("207", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"九条車庫"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"八条口207": {number: `${route("", sizeTop(scaleXC("207", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"八条口"+"</span>", 3.5, 1, "", 3), color: "loop"},
	"208": {number: Center.getCenter("208", 1.5, 1, "100%", 2), sub: "", color: "loop"},
	"九条車庫208": {number: `${route("", sizeTop(scaleXC("208", 1.3), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"九条車庫"+"</span>", 3.5, 1, "", 4), color: "loop"},
	"特208": {number: `${Center.getCenter(route("特", "208", ""), 1.5, 1, "", 2.7)}`, sub: "", color: "loop"},
	/* 300番台 */
	"300": {number: Center.getCenter("300", 1.5, 1, "100%", 2), sub: "", color: "normal"},
	/* 北 系統 */
	"北1": {number: `${Center.getCenter(route("北", "1", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "normal"},
	"北2": {number: `${Center.getCenter(route("北", "2", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "normal"},
	"北3": {number: `${Center.getCenter(route("北", "3", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特北3": {number: `${Center.getCenter(route("特北", "3", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"北4": {number: `${Center.getCenter(route("北", "4", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"臨北4": {number: `${Center.getCenter(route("臨北", "4", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"北5": {number: `${Center.getCenter(route("北", "5", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"北6": {number: `${Center.getCenter(route("北", "6", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"臨北6": {number: `${Center.getCenter(route("臨北", "6", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"北8": {number: `${Center.getCenter(route("北", "8", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"北大路BT8": {number: sizeTop(scaleXC(`<span style="display: inline-block; font-size: 80%; transform: translateY(-0.07em); font-weight: 600;">北</span>8`, 1.3), "65%"), sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"北大路BT"+"</span>", 3.5, 1, "", 4), color: "seiriken"},
	/* 西 系統 */
	"西1": {number: `${Center.getCenter(route("西", "1", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"西2": {number: `${Center.getCenter(route("西", "2", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西2": {number: `${Center.getCenter(route("特西", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"臨西2": {number: `${Center.getCenter(route("臨西", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"環西2": {number: `${Center.getCenter(route("環西", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"西3": {number: `${Center.getCenter(route("西", "3", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西3": {number: `${Center.getCenter(route("特西", "3", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"MN特西3": {number: `${route("", sizeTop(scaleXC(route("特西", "3", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px) scaleX(1.2)\">"+"ＭＮ"+"</span>", 3.5, 1, "", 3), color: "seiriken"},
	"西4": {number: `${Center.getCenter(route("西", "4", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西4": {number: `${Center.getCenter(route("特西", "4", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"西5": {number: `${Center.getCenter(route("西", "5", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西5": {number: `${Center.getCenter(route("特西", "5", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"臨西5": {number: `${Center.getCenter(route("臨西", "5", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"西6": {number: `${Center.getCenter(route("西", "6", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西6": {number: `${Center.getCenter(route("特西", "6", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"西7": {number: `${Center.getCenter(route("西", "7", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特西7": {number: `${Center.getCenter(route("特西", "7", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"西8": {number: `${Center.getCenter(route("西", "8", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	/* 東 系統 */
	"東1": {number: `${Center.getCenter(route("東", "1", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"東2": {number: `${Center.getCenter(route("東", "2", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特東2": {number: `${Center.getCenter(route("特東", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"東3": {number: `${Center.getCenter(route("東", "3", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"東4": {number: `${Center.getCenter(route("東", "4", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特東4": {number: `${Center.getCenter(route("特東", "4", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"東5": {number: `${Center.getCenter(route("東", "5", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"東6": {number: `${Center.getCenter(route("東", "6", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特東6": {number: `${Center.getCenter(route("特東", "6", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"東7": {number: `${Center.getCenter(route("東", "7", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"東8": {number: `${Center.getCenter(route("東", "8", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"東9": {number: `${Center.getCenter(route("東", "9", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特東9": {number: `${Center.getCenter(route("特東", "9", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"東10": {number: `${Center.getCenter(route("東", "10", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "seiriken"},
	/* 南 系統 */
	"南1": {number: `${Center.getCenter(route("南", "1", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特南1": {number: `${Center.getCenter(route("特南", "1", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"臨南1": {number: `${Center.getCenter(route("臨南", "1", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"南2": {number: `${Center.getCenter(route("南", "2", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特南2": {number: `${Center.getCenter(route("特南", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"臨南2": {number: `${Center.getCenter(route("臨南", "2", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"南3": {number: `${Center.getCenter(route("南", "3", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特南3": {number: `${Center.getCenter(route("特南", "3", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"伏見港南3": {number: `${route("", sizeTop(scaleXC(route("南", "3", ""), 1.0), "65%"), "")}`, sub: Center.getCenter("<span style=\"display: inline-block; transform: translateY(2.5px)\">"+"伏見港"+"</span>", 3.5, 1, "", 3), color: "seiriken"},
	"南4": {number: `${Center.getCenter(route("南", "4", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "normal"},
	"南5": {number: `${Center.getCenter(route("南", "5", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"特南5": {number: `${Center.getCenter(route("特南", "5", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"臨南5": {number: `${Center.getCenter(route("臨南", "5", ""), 1.5, 1, "", 2.5)}`, sub: "", color: "seiriken"},
	"南6": {number: `${Center.getCenter(route("南", "6", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"南7": {number: `${Center.getCenter(route("南", "7", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	"南8": {number: `${Center.getCenter(route("南", "8", ""), 1.5, 1, "", 1.5)}`, sub: "", color: "seiriken"},
	/* その他系統 */
	"M1": {number: "M1", sub: "", color: "normal"},
	"特M1": {number: `${Center.getCenter(route("特", "M1", ""), 1.5, 1, "", 2.2)}`, sub: "", color: "normal"},
	"臨": {number: scaleXC(route("臨", "", ""), 1.2), sub: "", color: "normal"},
	"急行": {number: route("", sizeBottom(scaleXC(route("急行", "", ""), 1.0), "65%"), ""), sub: `Express`, color: "normal", isReverse: true},
	"二条城金閣寺EXP": {number: route("", sizeBottom(scaleXC(route("<span style='line-height: 1; transform: scaleY(0.5) scaleX(0.6) translateX(0.5em); display: inline-block; transform-origin: bottom left; letter-spacing: 0.5em;'>二条城<br>金閣寺<span>", "", ""), 1.0), "65%"), ""), sub: `Express`, color: "normal", isReverse: true},
	"永観堂銀閣寺EXP": {number: route("", sizeBottom(scaleXC(route("<span style='line-height: 1; transform: scaleY(0.5) scaleX(0.6) translateX(0.5em); display: inline-block; transform-origin: bottom left; letter-spacing: 0.5em;'>永観堂<br>銀閣寺<span>", "", ""), 1.0), "65%"), ""), sub: `Express`, color: "normal", isReverse: true},
};

const KYOTO_CITY_BUS = {
	/* 西賀茂車 1号系統 */
	"西賀茂_1_出町柳": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["1"], "", `${Center.getCenter("北大路バスターミナル", 7.5, 1, "1rem")}\n下鴨神社`, `${size("出町柳駅", "2.5rem")}`, "Demachiyanagi Sta."),
	"西賀茂_1_西賀茂": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["1"], "", `佛教大学`, `${size("西賀茂車庫", "2.5rem")}`, "Nishigamo"),
	/* 西賀茂車 4号系統 */
	"西賀茂_4_四条河原町・京都駅":		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["4"], "河原町通", ``, `${Center.getCenter("四条河原町･京都駅", 8, 1, "2rem")}`, `${letterSpacing("Kyoto Sta. Via Shijoo Kawaramachi", "1.3px")}`),
	"西賀茂_4_京都駅":					new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["4"], "河原町通", ``, `${size("京都駅", "2rem")}`, `Kyoto Sta.`),
	"西賀茂_4_四条河原町・上賀茂神社":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["4"], "河原町通", ``, `${Center.getCenter("四条河原町･上賀茂神社", 8, 1, "2rem")}`, `Kamigamo-jinja Shrine`),
	"西賀茂_4_出町柳駅・上賀茂神社":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["4"], "河原町通", `出町柳駅\n下鴨神社`, `${sizeWidth("上賀茂神社", "2rem", "6em")}`, `Kamigamo-jinja Shrine`),
	"西賀茂_4_上賀茂神社":				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["4"], "", ``, `${size("上賀茂神社", "2.5rem")}`, `Kamigamo-jinja Shrine`),
	/* 西賀茂車 特4号系統 */
	"西賀茂_特4_四条河原町・京都駅": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["松ヶ崎4"], "河原町通", ``, `${Center.getCenter("四条河原町･京都駅", 8, 1, "2rem")}`, `${letterSpacing("Kyoto Sta. Via Shijoo Kawaramachi", "1.5px")}`),
	"西賀茂_特4_四条河原町・上賀茂神社":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["松ヶ崎4"], "河原町通", ``, `${Center.getCenter("四条河原町･上賀茂神社", 8, 1, "2rem")}`, `Kamigamo-jinja Shrine`),
	"西賀茂_特4_上賀茂神社":				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["上賀茂小4"], "", ``, `${sizeWidth("上賀茂神社", "2.5rem", "6em")}`, `Kamigamo-jinja Shrine`),
	/* 西賀茂車 9号系統 */
	"西賀茂_9_二条城・京都駅":				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["9"], "堀川通", ``, `${sizeWidth("二条城･京都駅", "2rem", "7em")}`, `${letterSpacing("Kyoto Sta. Via Nijo-jo Castle", "2px")}`),
	"西賀茂_9_京都駅":						new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["9"], "堀川通", ``, `${size("京都駅", "2rem")}`, `Kyoto Sta.`),
	"西賀茂_9_二条城・西賀茂車庫":			new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["9"], "堀川通", ``, `${scaleXL(sizeMax("二条城･西賀茂車庫", "2rem", "8em"), 8.5 / 9)}`, `${letterSpacing("Nishigamo Via Nijo-jo Castle", "2px")}`),
	"西賀茂_9_上賀茂御薗橋・西賀茂車庫":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["9"], "堀川通", `上賀茂御薗橋`, `${size("西賀茂車庫", "2rem")}`, `Nishigamo`),
	/* 西賀茂車 37号系統 */
	"西賀茂_37_北大路BT・四条河原町": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["37"], "", ``, `${kitaojiBT(7, 1.25)}<span style="transform: translateY(5px); display: inline-block;">${Center.getCenter("･四条河原町", 4, 1, "2rem")}</span>`, `Shijo Kawaramachi`),
	"西賀茂_37_四条河原町・三条京阪": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["37"], "河原町通", ``, `${Center.getCenter("四条河原町･三条京阪", 8, 1, "2rem")}`, `Shijo Kawaramachi`),
	"西賀茂_37_四条河原町・三条京阪まで": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["37"], "河原町通", ``, `${Center.getCenter("四条河原町･三条京阪"+made(), 7, 1, "2rem", 9.5)}`, `Shijo Kawaramachi`),
	"西賀茂_37_北大路BT・西賀茂車庫": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["37"], "河原町通", ``, `${kitaojiBT(8, 1)}${Center.getCenter("･西賀茂車庫", 4, 1, "2rem")}`, `${letterSpacing("Nishigamo Via Kitaoji Bus Terminal", "1.4px")}`),
	"西賀茂_37_上賀茂御薗橋・西賀茂車庫": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["37"], "堀川通", `上賀茂御薗橋`, `${size("西賀茂車庫", "2rem")}`, `Nishigamo`),
	/* 西賀茂車 46号系統 */
	"西賀茂_46_四条河原町・平安神宮": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["46"], "千本通", ``, `${Center.getCenter("四条河原町･平安神宮", 8, 1, "2rem")}`, `Shijo Kawaramachi`),
	"西賀茂_46_祇園・平安神宮": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["46"], "", ``, `${Center.getCenter("祇園･平安神宮", 7, 1, "2.5rem")}`, `Heian-jingu Shrine Via Gion`),
	"西賀茂_46_四条河原町・上賀茂神社":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["46"], "千本通", ``, `${Center.getCenter("四条河原町･上賀茂神社", 8, 1, "2rem")}`, `Shijo Kawaramachi`),
	"西賀茂_46_上賀茂神社": 			new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["46"], "千本通", `佛教大学\n下鴨神社`, `${Center.getCenter("上賀茂神社", 6, 1, "2rem")}`, `Kamigamo-jinja Shrine`),
	/* 西賀茂車 67号系統 */
	"西賀茂_67_四条大宮・松尾橋": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["67"], "堀川通", ``, `${Center.getCenter("四条大宮･松尾橋", 8, 1, "2rem")}`, `Matsuobashi`),
	"西賀茂_67_京都外大・松尾橋": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["67"], "", `京都外大`, `${Center.getCenter("松尾橋", 5, 1, "2.5rem")}`, `Matsuobashi`),
	"西賀茂_67_上賀茂神社": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["67"], "堀川通", ``, `${Center.getCenter("上賀茂神社", 8, 1, "2rem")}`, `Kamigamo-jinja Shrine`),
	/* 西賀茂車 51号系統 */
	"西賀茂_51_烏丸御池・四条河原町まで":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["51"], "", `烏丸御池`, `${Center.getCenter("四条河原町"+made(), 5.4, 1, "2.5rem", 7)}`, `Shijo Kawaramachi`),
	"西賀茂_51_四条河原町・三条京阪": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["51"], "", ``, `${Center.getCenter("四条河原町･三条京阪", 7, 1, "2.5rem")}`, `Shijo Kawaramachi`),
	"西賀茂_51_北野天満宮・立命館大学": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["51"], "", `北野天満宮`, `${Center.getCenter("立命館大学", 4.9, 1, "2.5rem")}`, `Ritsumeikan Univ.`),
	/* 西賀茂車 12号系統 */
	"西賀茂_12_堀川通_四条河原町・三条京阪":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "堀川通", ``, `${Center.getCenter("四条河原町･三条京阪", 8, 1, "2rem")}`, `Shijo Kawaramachi`),
	"西賀茂_12_四条河原町・三条京阪":			new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "", ``, `${Center.getCenter("四条河原町･三条京阪", 7, 1, "2.5rem")}`, `Shijo Kawaramachi`),
	"西賀茂_12_二条城・金閣寺・立命館大学": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "堀川通", `${scaleXL("二条城", 0.9)}`, `${Center.getCenter("四条河原町･三条京阪", 6.4, 1, "2rem")}`, `${letterSpacing("Kinkakuji Temple Via Nijo-jo Castle", "1.5px")}`),
	"西賀茂_12_堀川通_金閣寺・立命館大学": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "堀川通", ``, `${Center.getCenter("金閣寺･立命館大学", 8, 1, "2rem")}`, `Kinkakuji Temple`),
	"西賀茂_12_金閣寺・立命館大学": 			new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "", ``, `${Center.getCenter("金閣寺･立命館大学", 7, 1, "2.5rem")}`, `Kinkakuji Temple`),
	"西賀茂_12_四条河原町・三条京阪まで": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["12"], "", ``, `${Center.getCenter("四条河原町･三条京阪"+made(), 6, 1, "2.5rem", 9.5)}`, `Shijo Kawaramachi`),
	/* 西賀茂車 15号系統 */
	"西賀茂_15_四条河原町・三条京阪": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["15"], "", ``, `${Center.getCenter("四条河原町･三条京阪", 7, 1, "2.5rem")}`, `Shijo Kawaramachi`),
	"西賀茂_15_円町・立命館大学": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["15"], "", `円町`, `${Center.getCenter("立命館大学", 6, 1, "2.5rem")}`, `Ritsumeikan Univ.`),
	/* 西賀茂車 55号系統 */
	"西賀茂_55_二条駅・四条大宮・四条烏丸": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["55"], "千本通", `二条駅\n四条大宮`, `${Center.getCenter("四条烏丸", 6, 1, "2rem")}`, `Shijo Karasuma`),
	"西賀茂_55_四条烏丸": 					new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["55"], "", ``, `${Center.getCenter("四条烏丸", 6, 1, "2.5rem")}`, "Shijo Karasuma"),
	"西賀茂_55_北野天満宮・立命館大学": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["55"], "千本通", `北野天満宮`, `${sizeWidth("立命館大学", "2rem", "5.5em")}`, `Ritsumeikan Univ.`),
	"西賀茂_55_立命館大学": 				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["55"], "", ``, `${Center.getCenter("立命館大学", 6, 1, "2.5rem")}`, `Ritsumeikan Univ.`),
	/* 西賀茂車 北1号系統 */
	"西賀茂_北1_玄琢下まで":	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["北1"], "", `佛教大学`, `${Center.getCenter("玄琢下 "+made(), 5, 1, "2.5rem", 4)}`, `Bukkyo Univ.`),
	/* 西賀茂車 北大路BT205号系統 */
	"西賀茂_北大路BT205_四条河原町・北大路BT": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["北大路BT205"], "河原町通", ``, `${Center.getCenter("四条河原町･", 3, 1, "2rem")}<span style="transform: translateY(-0.4em);">${kitaojiBT(4, 2, 1)}</span><span style="transform: translateY(-0.4em);">${Center.getCenter(made(), 1, 1, "2rem", 1.5)}</span>`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Shijo Kawaramachi", 15, 1, "0.8rem", 16), "0")}`),
	"西賀茂_北大路BT205_下鴨神社・北大路BT": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["北大路BT205"], "河原町通", ``, `${Center.getCenter("下鴨神社･", 2.75, 1, "2rem")}<span style="transform: translateY(-0.4em);">${kitaojiBT(4.25, 2, 1)}</span><span style="transform: translateY(-0.4em);">${Center.getCenter(made(), 1, 1, "2rem", 1.5)}</span>`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Shimogamo-jinja Shrine", 15, 1, "0.8rem", 18), "0")}`),
	"西賀茂_北大路BT205_北大路BT":				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["北大路BT205"], "", ``, `${kitaojiBT(7.5, 2, 1)}</span>${Center.getCenter(made(), 1, 1, "2rem", 1.5)}`, `Kitaoji Bus Terminal`),
	"西賀茂_北大路BT205_金閣寺・北大路BT": 		new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["北大路BT205"], "西大路通", ``, `${Center.getCenter("金閣寺･", 2.5, 1, "2rem")}<span style="transform: translateY(-0.4em);">${kitaojiBT(4.5, 2, 1)}</span><span style="transform: translateY(-0.4em);">${Center.getCenter(made(), 1, 1, "2rem", 1.5)}</span>`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	/* 西賀茂車 京都駅205号系統 */
	"西賀茂_京都駅205_西大路四条・西大路七条・京都駅まで": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["京都駅205"], "西大路通", `西大路四条\n西大路七条`, `<span style="transform: translateY(-0.4em);">${Center.getCenter("京都駅", 3, 1, "2.5rem")}</span>${Center.getCenter(made(), 1.5, 1, "2rem", 1.5)}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	"西賀茂_京都駅205_京都駅まで": 							new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["京都駅205"], "", ``, `${Center.getCenter("京都駅", 3, 1, "2.5rem")}${Center.getCenter(made(), 1.5, 1.5, "2rem", 1.5)}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	/* 西賀茂車 快速205号系統 */
	"西賀茂_快速205_北野白梅町・立命館大学": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["快速205"], "", `北野白梅町`, `${sizeWidth("立命館大学", "2rem", "5.5em")}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	"西賀茂_快速205_西大路四条・京都駅まで": 	new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["快速205"], "西大路通", `西大路四条`, `${Center.getCenter("京都駅", 3.5, 1, "2rem")}${Center.getCenter(made(), 1.5, 1, "2rem", 1.5)}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	"西賀茂_快速205_京都駅まで": 				new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["快速205"], "", ``, `${Center.getCenter("京都駅", 3, 1, "2.5rem")}${Center.getCenter(made(), 1.5, 1.5, "2rem", 1.5)}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	
	"西賀茂_臨_快速・佛教大学": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", `<span style="border: 1px solid white; font-size: 1.5em;">快速</span>`, `<span style="transform: translatey(-5px);">${Center.getCenter("佛教大学", 3.75, 0.9, "3.5rem")}</span>`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	"西賀茂_急行_祇園・清水寺": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行"], "東山通", ``, `${Center.getCenter("清水寺･祇園", 6, 1, "2rem")}`, `${letterSpacing(Center.getCenter("Kitaoji Bus Terminal Via Kinkakuji Temple", 15, 1, "0.8rem", 17), "0")}`),
	/* 西賀茂車 6号系統 */
	"西賀茂_6_二条駅・四条大宮": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["6"], "千本通", ``, `${Center.getCenter("二条駅･四条大宮", 8, 1, "2rem")}`, `Kinkakuji Temple`),
	/* 西賀茂車 急行100系統 */
	"西賀茂_急行100_清水寺・銀閣寺": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行100"], "", ``, `${Center.getCenter("清水寺･銀閣寺", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行100_平安神宮・銀閣寺": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行100"], "", ``, `${Center.getCenter("平安神宮･銀閣寺", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行100_祇園・清水寺・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行100"], "", `祇園\n清水寺`, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行100_清水寺・三十三間堂・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行100"], "", `清水寺\n三十三間堂`, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行101_金閣寺・北野天満宮・二条城": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行101"], "", ``, `${Center.getCenter("金閣寺･北野天満宮･二条城", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	/* 西賀茂車 急行101系統 */
	"西賀茂_急行101_二条城・四条烏丸・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行101"], "", `二条城\n四条烏丸`, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行101_二条城・北野天満宮・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行101"], "", `二条城\n北野天満宮`, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行101_金閣寺・大徳寺・北大路BT": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行101"], "", `金閣寺\n大徳寺`, `<span style="transform: translateY(-.5em);">${kitaojiBT(8, 1.75)}</span>`, `Kinkakuji Temple`, true),
	/* 西賀茂車 急行102系統 */
	"西賀茂_急行102_北野天満宮・金閣寺": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行102"], "", ``, `${Center.getCenter("北野天満宮･金閣寺", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行102_金閣寺・大徳寺・北大路BT": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行102"], "", `金閣寺\n大徳寺`, `<span style="transform: translateY(-.5em);">${kitaojiBT(8, 1.75)}</span>`, `Kinkakuji Temple`, true),
	"西賀茂_急行102_金閣寺・北野天満宮": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行102"], "", ``, `${Center.getCenter("金閣寺･北野天満宮", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_急行102_出町柳駅・銀閣寺・錦林車庫": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行102"], "", `出町柳駅`, `${Center.getCenter("銀閣寺･錦林車庫", 5, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	/* 西賀茂車 臨時系統 */
	"西賀茂_臨_出町柳駅・銀閣寺・錦林車庫": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "東山通", ``, `${Center.getCenter("清水寺･祇園･三条京阪", 8, 1, "2rem")}`, `Kinkakuji Temple`),
	"西賀茂_臨_清水寺・三十三間堂・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "東山通", `清水寺\n三十三間堂`, `${Center.getCenter("京都駅", 5, 1, "2rem")}`, `Kinkakuji Temple`),
	"西賀茂_臨_京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", ``, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`),
	"西賀茂_臨_三条京阪まで": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", ``, `${Center.getCenter("三条京阪"+made(), 5, 1, "2.5rem", 5)}`, `Kinkakuji Temple`),
	"西賀茂_二条城金閣寺EXP": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["二条城金閣寺EXP"], "", ``, `${Center.getCenter("京都駅↔︎二条城↔︎金閣寺", 7, 1, "2.5rem")}`, `Kinkakuji Temple`),
	"西賀茂_永観堂銀閣寺EXP": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["永観堂銀閣寺EXP"], "", ``, `${Center.getCenter("京都駅↔︎四条河原町↔︎銀閣寺", 7, 1, "2.5rem")}`, `Kinkakuji Temple`),
	"西賀茂_急行103_京都駅↔︎水族館・鉄道博物館": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行103"], "", ``, `${Center.getCenter("京都駅↔︎水族館･鉄道博物館", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_臨_吉田神社↔︎京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", ``, `${Center.getCenter("吉田神社↔︎京都駅", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_臨_吉田神社↔︎壬生寺": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", ``, `${Center.getCenter("吉田神社↔︎壬生寺", 7.1, 1, "2.5rem")}`, `Kinkakuji Temple`, true),
	"西賀茂_臨_三条京阪・四条河原町・京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["臨"], "", `三条京阪\n四条河原町`, `${Center.getCenter("京都駅", 5, 1, "2.5rem")}`, `Kinkakuji Temple`),
	"西賀茂_急行106_清水寺・祇園": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行106"], "東山通", ``, `${Center.getCenter("清水寺･祇園", 7, 1, "2rem")}`, `Kinkakuji Temple`),
	"西賀茂_急行106_京都駅": new HokomakuInfo(KYOTO_CITY_BUS_ROUTE["急行106"], "河原町通", ``, `${Center.getCenter("京都駅", 7, 1, "2rem")}`, `Kinkakuji Temple`),
}